from .Yuan_Tool import NODE_CLASS_MAPPINGS as TOOL_MAPPINGS
from .Yuan_Tool import NODE_DISPLAY_NAME_MAPPINGS as TOOL_DISPLAY_MAPPINGS
from .Yuan_TXT import NODE_CLASS_MAPPINGS as TXT_MAPPINGS
from .Yuan_TXT import NODE_DISPLAY_NAME_MAPPINGS as TXT_DISPLAY_MAPPINGS
from .Yuan_CLIP_Timeline import NODE_CLASS_MAPPINGS as CLIP_TIMELINE_MAPPINGS
from .Yuan_CLIP_Timeline import NODE_DISPLAY_NAME_MAPPINGS as CLIP_TIMELINE_DISPLAY_MAPPINGS
from .Yuan_Clip_Guide import NODE_CLASS_MAPPINGS as CLIP_GUIDE_MAPPINGS
from .Yuan_Clip_Guide import NODE_DISPLAY_NAME_MAPPINGS as CLIP_GUIDE_DISPLAY_MAPPINGS
from .Yuan_Panorama import NODE_CLASS_MAPPINGS as PANORAMA_MAPPINGS
from .Yuan_Panorama import NODE_DISPLAY_NAME_MAPPINGS as PANORAMA_DISPLAY_MAPPINGS
from .Yuan_ColorMatch import NODE_CLASS_MAPPINGS as COLORMATCH_MAPPINGS
from .Yuan_ColorMatch import NODE_DISPLAY_NAME_MAPPINGS as COLORMATCH_DISPLAY_MAPPINGS
from .Yuan_Canvas import NODE_CLASS_MAPPINGS as CANVAS_MAPPINGS
from .Yuan_Canvas import NODE_DISPLAY_NAME_MAPPINGS as CANVAS_DISPLAY_MAPPINGS
from .Yuan_MultiImage import NODE_CLASS_MAPPINGS as MULTIIMAGE_MAPPINGS
from .Yuan_MultiImage import NODE_DISPLAY_NAME_MAPPINGS as MULTIIMAGE_DISPLAY_MAPPINGS
from .MiniMax_H3 import NODE_CLASS_MAPPINGS as MM3_MAPPINGS
from .MiniMax_H3 import NODE_DISPLAY_NAME_MAPPINGS as MM3_DISPLAY_MAPPINGS
from .Yuan_H3_Motion import NODE_CLASS_MAPPINGS as H3_MOTION_MAPPINGS
from .Yuan_H3_Motion import NODE_DISPLAY_NAME_MAPPINGS as H3_MOTION_DISPLAY_MAPPINGS
from .Yuan_RTX_Upscale import NODE_CLASS_MAPPINGS as RTX_MAPPINGS
from .Yuan_RTX_Upscale import NODE_DISPLAY_NAME_MAPPINGS as RTX_DISPLAY_MAPPINGS
from .Yuan_H3_Upscale import NODE_CLASS_MAPPINGS as H3_UPSCALE_MAPPINGS
from .Yuan_H3_Upscale import NODE_DISPLAY_NAME_MAPPINGS as H3_UPSCALE_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **TOOL_MAPPINGS,
    **TXT_MAPPINGS,
    **CLIP_TIMELINE_MAPPINGS,
    **CLIP_GUIDE_MAPPINGS,
    **PANORAMA_MAPPINGS,
    **COLORMATCH_MAPPINGS,
    **CANVAS_MAPPINGS,
    **MULTIIMAGE_MAPPINGS,
    **MM3_MAPPINGS,
    **H3_MOTION_MAPPINGS,
    **RTX_MAPPINGS,
    **H3_UPSCALE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TOOL_DISPLAY_MAPPINGS,
    **TXT_DISPLAY_MAPPINGS,
    **CLIP_TIMELINE_DISPLAY_MAPPINGS,
    **CLIP_GUIDE_DISPLAY_MAPPINGS,
    **PANORAMA_DISPLAY_MAPPINGS,
    **COLORMATCH_DISPLAY_MAPPINGS,
    **CANVAS_DISPLAY_MAPPINGS,
    **MULTIIMAGE_DISPLAY_MAPPINGS,
    **MM3_DISPLAY_MAPPINGS,
    **H3_MOTION_DISPLAY_MAPPINGS,
    **RTX_DISPLAY_MAPPINGS,
    **H3_UPSCALE_DISPLAY_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
