from .Yuan_Tool import NODE_CLASS_MAPPINGS as TOOL_MAPPINGS
from .Yuan_Tool import NODE_DISPLAY_NAME_MAPPINGS as TOOL_DISPLAY_MAPPINGS
from .Yuan_TXT_Splitter import NODE_CLASS_MAPPINGS as TXT_MAPPINGS
from .Yuan_TXT_Splitter import NODE_DISPLAY_NAME_MAPPINGS as TXT_DISPLAY_MAPPINGS
from .Yuan_TXT_ListNumber import NODE_CLASS_MAPPINGS as LISTNUMBER_MAPPINGS
from .Yuan_TXT_ListNumber import NODE_DISPLAY_NAME_MAPPINGS as LISTNUMBER_DISPLAY_MAPPINGS
from .Yuan_TXT_ConvertAny import NODE_CLASS_MAPPINGS as CONVERTANY_MAPPINGS
from .Yuan_TXT_ConvertAny import NODE_DISPLAY_NAME_MAPPINGS as CONVERTANY_DISPLAY_MAPPINGS
from .Yuan_CLIP_Timeline import NODE_CLASS_MAPPINGS as CLIP_TIMELINE_MAPPINGS
from .Yuan_CLIP_Timeline import NODE_DISPLAY_NAME_MAPPINGS as CLIP_TIMELINE_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **TOOL_MAPPINGS,
    **TXT_MAPPINGS,
    **LISTNUMBER_MAPPINGS,
    **CONVERTANY_MAPPINGS,
    **CLIP_TIMELINE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TOOL_DISPLAY_MAPPINGS,
    **TXT_DISPLAY_MAPPINGS,
    **LISTNUMBER_DISPLAY_MAPPINGS,
    **CONVERTANY_DISPLAY_MAPPINGS,
    **CLIP_TIMELINE_DISPLAY_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
